name: Build MkDocs Artifacts
description: Build MkDocs and Versioning with Mike

inputs:
  docs-version:
    description: "Docs Version"
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Setup gh-pages Branch
      shell: bash
      run: |
        if ! git ls-remote --heads origin gh-pages | grep -q gh-pages; then
          CURRENT_BRANCH=$(git branch --show-current)
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout "$CURRENT_BRANCH"
        fi

    - name: Build and Deploy Docs
      shell: bash
      run: |
        uv run mike deploy --push --update-aliases "${{ inputs.docs-version }}" latest
        uv run mike set-default --push latest
