nav:
  - Home: index.md
  - Course:
      - course/Mathematics/
      - course/Computer Vision/
      - course/Sequential Models/
      - course/Generative/
      - course/Graphs/
      - course/Time Series/
sort:
  ignore_case: true
  type: alphabetical
